targets:
  $default:
    sources:
      - lib/**
      - swagger/**
      - $package$
    builders:
      swagger_dart_code_generator:
        options:
          input_folder: "swagger/"
          output_folder: "lib/swagger_generated_code_v2/"