targets:
  $default:
    sources:
      - lib/**
      - swaggers/**
      - $package$
    builders:
      swagger_dart_code_generator:
        options:
          build_only_models: true
          input_folder: "swagger_files/"
          output_folder: "lib/api_lib/"