name: coursecupid
description: Coures Matching Application

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+10

environment:
  sdk: ">=2.16.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  reactive_forms: ^11.0.1
  cupertino_icons: ^1.0.2
  package_info_plus: ^1.4.0
  flutter_secure_storage: ^5.0.2
  flutter_appauth: ^2.4.1
  google_fonts: ^2.3.1
  http: ^0.13.4
  json_annotation: ^4.4.0
  logger: ^1.1.0
  json_serializable: ^6.1.4
  lottie: ^1.2.2
  english_words: ^4.0.0
  chopper: ^4.0.1
  badges: ^2.0.2
  dropdown_search: ^2.0.1
  json_theme: ^3.3.1
  expandable: ^5.0.1
  fluttertoast: ^8.0.9
  pull_to_refresh: ^2.0.0
  url_launcher: ^6.0.20
  dynamic_themes: ^1.1.0
  firebase_core: ^1.14.0
  firebase_messaging: ^11.2.12
  overlay_support: ^1.2.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.4
  chopper_generator: ^4.0.2
  swagger_dart_code_generator: 2.4.2
  flutter_lints: ^1.0.0
  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icon/logo.png"
  remove_alpha_ios: true

# The following section is specific to Flutter.
flutter:
  assets:
    - env/
    - assets/theme/stary_night.json
    - assets/theme/dark_forest.json
    - assets/theme_main.json
    - assets/register.json
    - assets/cupid-arrow.png
    - assets/loading.json
    - assets/astronaout.json
    - assets/cat.json
    - assets/chemical.json
    - assets/coffee.json
    - assets/cow.json
    - assets/dogNewsPaper.json
    - assets/dogSmell.json
    - assets/dogSwimming.json
    - assets/emptybox.json
    - assets/icecream.json
    - assets/laptop.json
    - assets/lochness.json
    - assets/puzzle.json
    - assets/tissue.json

  uses-material-design: true


