name: coursecupid
description: Coures Matching Application

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  reactive_forms: ^11.0.1
  cupertino_icons: ^1.0.2
  package_info_plus: ^1.4.0
  flutter_secure_storage: ^5.0.2
  flutter_appauth: ^2.4.1
  google_fonts: ^2.3.1
  http: ^0.13.4
  json_annotation: ^4.4.0
  logger: ^1.1.0
  json_serializable: ^6.1.4
  lottie: ^1.2.2
  english_words: ^4.0.0
  chopper: ^4.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.4
  chopper_generator: ^4.0.2
  swagger_dart_code_generator: any
  flutter_lints: ^1.0.0

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/cupid-arrow.png
    - assets/loading.json
    - assets/astronaout.json
    - assets/cat.json
    - assets/chemical.json
    - assets/coffee.json
    - assets/cow.json
    - assets/dogNewsPaper.json
    - assets/dogSmell.json
    - assets/dogSwimming.json
    - assets/emptybox.json
    - assets/icecream.json
    - assets/laptop.json
    - assets/lochness.json
    - assets/puzzle.json
    - assets/tissue.json

  uses-material-design: true


